### ISSUE TITLE
Time until next event

### ISSUE THREAD

**Issue by yannickgr** [yannickgr/PieWatchFace#3]
When we have an upcoming event, and the pie piece is big enough for more than just the title, we should show a countdown in minutes until this event. 
It could be displayed in a smaller and lighter font, and perhaps in italics. 
I think it would also be best to display it near the edge of the start of the pie piece, so not below the title like the location.

![screen-shot-2015-11-23-at-13 07 55](https://cloud.githubusercontent.com/assets/15957852/11336421/6f07f5ee-91e5-11e5-853e-70db43d5deb9.png)

**Comment by gurinderhans** [comment]
Done!

**Comment by yannickgr** [comment]
Looks nice!
There's still an issue I think though, the countdown remains on the lunch event for me, event when it's in the past (see I see a -x minutes countdown). And so, I don't see the countdown for the next upcoming event.

**Comment by gurinderhans** [comment]
This wouldn't heppen in a real life situation, since our next event will always be in the future and have a positive time difference.
